#############################
# Xups for Hexo 主题配置文件
# Jelon
# http://jelon.top
#############################

#----------------------------
# 头部导航
#----------------------------
menu:
  home:
    name: 首页
    link: /
    icon: icon-home
  lab:
    name: 项目
    link: /lab/
    icon: icon-lab
  about:
    name: 关于
    link: /about/
    icon: icon-about
  comment:
    name: 留言
    link: /comment/
    icon: icon-comment

#----------------------------
# 副导航
#----------------------------
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"

#----------------------------
# RSS
#----------------------------
rss: /atom.xml

#----------------------------
# Favicon
#----------------------------
favicon: /favicon.ico

#----------------------------
# 头像url
#----------------------------
avatar: /img/zhj.jpg

#----------------------------
# 是否开启分享
#----------------------------
share: true

#----------------------------
# 侧栏是否显示微博秀
#----------------------------
weibo_show:
  enable: false
  code: <iframe id="myWeibo" width="100%" height="550" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=2&ptype=1&speed=0&skin=1&isTitle=0&noborder=0&isWeibo=1&isFans=0&uid=2376003112&verifier=796ea597&dpc=1"></iframe>

#----------------------------
# 是否开启评论
#----------------------------
comment:
  enable: true
  owner: HuajingZeng
  repo: huajingzeng.github.io_comments
  client_id: 7ae3915c563a60d41451
  client_secret: 2abefe41031e15eabf12a828f30fd380487fb738

#----------------------------
# 是否开启云标签
#----------------------------
tagcloud: true

#----------------------------
# 友情链接
#----------------------------
friends:
  enable: true
  list:
    1:
      name: Stack Overflow
      title: Stack Overflow
      link: https://stackoverflow.com/
    2:
      name: NSHipster
      title: NSHipster
      link: http://nshipster.cn/
    3:
      name: raywenderlich
      title: raywenderlich
      link: https://www.raywenderlich.com/
    4:
      name: Cocoa China
      title: Cocoa China
      link: http://www.cocoachina.com/
    5:
      name: ObjC 中国
      title: ObjC 中国
      link: https://objccn.io/
    6:
      name: 未来软件园
      title: 未来软件园
      link: http://mac.orsoon.com/

#----------------------------
# 头部链接
#----------------------------
head_links:
  enable: true
  list:
    sup:
      0:
        name: Github
        link: https://github.com/HuajingZeng
      last:
        name: Hosted by Github Pages
        link: https://github.com
    sub:
      sinaweibo:
        name: 新浪微博
        link: https://weibo.com/p/1005051288040665/home?from=page_100505&mod=TAB#place
      qqweibo:
        name: Facebook
        link: 
#----------------------------
# SEO
#----------------------------
SEO:
  keywords: iOS, Web
  description: 曾华经个人博客

#----------------------------
# 百度分析
#----------------------------
baidu_analytics: true

#----------------------------
# 高亮样式
#----------------------------
highlight_theme: normal
#----------------------------
# CDN
# 如: //7xs305.com1.z0.glb.clouddn.com/
# 主要以下两个目录进行 cdn 存储
#   - img 图片资源下的 thumbnail 目录
#   - css 样式资源下的 fonts 目录
#----------------------------
CDN:
